USE codeup_test_db;
SELECT 'All albums';
SELECT * FROM albums;
UPDATE albums SET sales = sales * 10;
SELECT 'Albums released before 1980';
SELECT * FROM albums WHERE release_year < 1980;
UPDATE albums SET release_year = REPLACE(release_year, '19', '18') WHERE release_year < 1980;
SELECT 'Michael Jackson Albums';
SELECT * FROM albums WHERE artist = 'Michael Jackson';
UPDATE albums SET artist = REPLACE(artist, 'Michael Jackson', 'Michael Peter Jackson') WHERE artist = 'Michael Jackson';
